/**
 * Nomenclature NAF 2008 (rév. 2) — INSEE
 * Tous les codes avec leurs libellés officiels.
 */
export const NAF_LABELS: Record<string, string> = {
  // ── A – Agriculture, sylviculture et pêche
  "01.11Z": "Cultures céréalières",
  "01.12Z": "Culture du riz",
  "01.13Z": "Culture de légumes",
  "01.14Z": "Culture de canne à sucre",
  "01.15Z": "Culture du tabac",
  "01.16Z": "Culture de plantes à fibres",
  "01.19Z": "Autres cultures non permanentes",
  "01.21Z": "Culture de la vigne",
  "01.22Z": "Culture de fruits tropicaux",
  "01.23Z": "Culture d'agrumes",
  "01.24Z": "Culture de fruits à pépins",
  "01.25Z": "Culture d'autres fruits d'arbres",
  "01.26Z": "Culture de fruits oléagineux",
  "01.27Z": "Culture de plantes à boissons",
  "01.28Z": "Culture de plantes épices et aromatiques",
  "01.29Z": "Autres cultures permanentes",
  "01.30Z": "Reproduction de plantes",
  "01.41Z": "Élevage de vaches laitières",
  "01.42Z": "Élevage d'autres bovins",
  "01.43Z": "Élevage de chevaux",
  "01.44Z": "Élevage d'ovins et de caprins",
  "01.45Z": "Élevage de porcins",
  "01.46Z": "Élevage de volailles",
  "01.47Z": "Élevage d'autres animaux",
  "01.50Z": "Culture et élevage associés",
  "01.61Z": "Activités de soutien aux cultures",
  "01.62Z": "Activités de soutien à l'élevage",
  "01.63Z": "Traitement des récoltes",
  "01.64Z": "Traitement des semences",
  "01.70Z": "Chasse et piégeage",
  "02.10Z": "Sylviculture et autres activités forestières",
  "02.20Z": "Exploitation forestière",
  "02.30Z": "Récolte de produits forestiers",
  "02.40Z": "Services de soutien à l'exploitation forestière",
  "03.11Z": "Pêche en mer",
  "03.12Z": "Pêche en eau douce",
  "03.21Z": "Aquaculture en mer",
  "03.22Z": "Aquaculture en eau douce",

  // ── C – Industrie manufacturière (sélection des plus courants)
  "10.11Z": "Transformation et conservation de viande de boucherie",
  "10.12Z": "Transformation et conservation de volaille",
  "10.13A": "Préparation industrielle de produits à base de viande",
  "10.13B": "Charcuterie",
  "10.20Z": "Transformation et conservation de poisson",
  "10.31Z": "Transformation et conservation de pommes de terre",
  "10.32Z": "Préparation de jus de fruits et légumes",
  "10.39A": "Autre transformation de légumes",
  "10.41A": "Fabrication d'huiles et graisses",
  "10.51A": "Fabrication de lait liquide et de crème",
  "10.51B": "Fabrication de beurre",
  "10.51C": "Fabrication de fromages",
  "10.51D": "Fabrication d'autres produits laitiers",
  "10.52Z": "Fabrication de glaces et sorbets",
  "10.61A": "Meunerie",
  "10.71A": "Fabrication industrielle de pain",
  "10.71B": "Cuisson de produits de boulangerie",
  "10.71C": "Boulangerie et boulangerie-pâtisserie",
  "10.71D": "Pâtisserie",
  "10.72Z": "Fabrication de biscuits et gâteaux",
  "10.73Z": "Fabrication de pâtes alimentaires",
  "10.81Z": "Fabrication de sucre",
  "10.82Z": "Fabrication de cacao, chocolat",
  "10.83Z": "Transformation du thé et du café",
  "10.84Z": "Fabrication de condiments et assaisonnements",
  "10.85Z": "Fabrication de plats préparés",
  "10.86Z": "Fabrication d'aliments homogénéisés",
  "10.89Z": "Fabrication d'autres produits alimentaires",
  "10.91Z": "Fabrication d'aliments pour animaux de ferme",
  "10.92Z": "Fabrication d'aliments pour animaux de compagnie",
  "11.01Z": "Production de boissons alcooliques distillées",
  "11.02A": "Fabrication de vins effervescents",
  "11.02B": "Vinification",
  "11.03Z": "Fabrication de cidre",
  "11.04Z": "Production d'autres boissons fermentées",
  "11.05Z": "Fabrication de bière",
  "11.06Z": "Fabrication de malt",
  "11.07A": "Industrie des eaux de table",
  "11.07B": "Production de boissons rafraîchissantes",
  "13.10Z": "Préparation de fibres textiles",
  "14.11Z": "Fabrication de vêtements en cuir",
  "14.12Z": "Fabrication de vêtements de travail",
  "14.13Z": "Fabrication d'autres vêtements de dessus",
  "14.14Z": "Fabrication de vêtements de dessous",
  "14.19Z": "Fabrication d'autres vêtements",
  "14.20Z": "Fabrication d'articles en fourrure",
  "14.31Z": "Fabrication d'articles chaussants à mailles",
  "14.39Z": "Fabrication d'autres articles à mailles",
  "15.11Z": "Apprêt et tannage des cuirs",
  "15.12Z": "Fabrication d'articles de voyage et maroquinerie",
  "15.20Z": "Fabrication de chaussures",
  "16.10A": "Sciage et rabotage du bois",
  "16.10B": "Imprégnation du bois",
  "16.21Z": "Fabrication de placage et panneaux de bois",
  "16.22Z": "Fabrication de parquets assemblés",
  "16.23Z": "Fabrication de charpentes et menuiseries",
  "16.24Z": "Fabrication d'emballages en bois",
  "17.11Z": "Fabrication de pâte à papier",
  "17.12Z": "Fabrication de papier et carton",
  "17.21A": "Fabrication de carton ondulé",
  "17.21B": "Fabrication de cartonnages",
  "17.21C": "Fabrication d'emballages en papier",
  "17.22Z": "Fabrication d'articles en papier",
  "17.23Z": "Fabrication d'articles de papeterie",
  "17.24Z": "Fabrication de papiers peints",
  "17.29Z": "Fabrication d'autres articles en papier",
  "18.11Z": "Imprimerie de journaux",
  "18.12Z": "Autre imprimerie",
  "18.13Z": "Activités de pré-presse",
  "18.14Z": "Reliure et activités connexes",
  "18.20Z": "Reproduction d'enregistrements",
  "20.11Z": "Fabrication de gaz industriels",
  "20.12Z": "Fabrication de colorants",
  "20.13A": "Engrais et produits azotés",
  "20.14Z": "Fabrication d'autres produits chimiques",
  "20.15Z": "Fabrication de produits azotés",
  "20.16Z": "Fabrication de matières plastiques",
  "20.17Z": "Fabrication de caoutchouc synthétique",
  "20.20Z": "Fabrication de pesticides",
  "20.30Z": "Fabrication de peintures et vernis",
  "20.41Z": "Fabrication de savons et détergents",
  "20.42Z": "Fabrication de parfums et produits de toilette",
  "20.51Z": "Fabrication de produits explosifs",
  "20.59Z": "Fabrication d'autres produits chimiques",
  "20.60Z": "Fabrication de fibres artificielles",
  "21.10Z": "Fabrication de produits pharmaceutiques de base",
  "21.20Z": "Fabrication de préparations pharmaceutiques",
  "22.11Z": "Fabrication et rechapage de pneumatiques",
  "22.19Z": "Fabrication d'autres articles en caoutchouc",
  "22.21Z": "Fabrication de plaques en plastique",
  "22.22Z": "Fabrication d'emballages en matières plastiques",
  "22.23Z": "Fabrication d'éléments en plastique pour la construction",
  "22.29A": "Fabrication de pièces techniques en plastique",
  "22.29B": "Fabrication de produits de consommation courante en plastique",
  "23.11Z": "Fabrication de verre plat",
  "23.12Z": "Façonnage et transformation du verre plat",
  "23.13Z": "Fabrication de verre creux",
  "23.14Z": "Fabrication de fibres de verre",
  "23.19Z": "Fabrication et façonnage d'autres articles en verre",
  "23.20Z": "Fabrication de produits réfractaires",
  "23.31Z": "Fabrication de carreaux en céramique",
  "23.41Z": "Fabrication d'articles céramiques à usage domestique",
  "23.44Z": "Fabrication d'autres produits céramiques à usage technique",
  "23.51Z": "Fabrication de ciment",
  "23.52Z": "Fabrication de chaux et plâtre",
  "24.10Z": "Sidérurgie",
  "24.20Z": "Fabrication de tubes en acier",
  "24.31Z": "Étirage à froid de barres",
  "24.32Z": "Laminage à froid de feuillards",
  "24.33Z": "Profilage à froid par formage",
  "24.34Z": "Tréfilage à froid",
  "24.41Z": "Production de métaux précieux",
  "24.42Z": "Métallurgie de l'aluminium",
  "24.43Z": "Métallurgie du plomb, du zinc ou de l'étain",
  "24.44Z": "Métallurgie du cuivre",
  "24.45Z": "Métallurgie des autres métaux non ferreux",
  "24.46Z": "Élaboration et transformation de matières nucléaires",
  "25.11Z": "Fabrication de structures métalliques",
  "25.12Z": "Fabrication de portes et fenêtres en métal",
  "25.21Z": "Fabrication de radiateurs et chaudières",
  "25.29Z": "Fabrication d'autres réservoirs et conteneurs",
  "25.30Z": "Fabrication de générateurs de vapeur",
  "25.40Z": "Fabrication d'armes et de munitions",
  "25.50A": "Forge, estampage, matriçage",
  "25.50B": "Découpage, emboutissage",
  "25.61Z": "Traitement et revêtement des métaux",
  "25.62A": "Décolletage",
  "25.62B": "Mécanique industrielle",
  "25.71Z": "Fabrication de coutellerie",
  "25.72Z": "Fabrication de serrures et de ferrures",
  "25.73A": "Fabrication de moules et modèles",
  "25.73B": "Fabrication d'autres outillages",
  "25.91Z": "Fabrication de fûts et emballages métalliques",
  "25.92Z": "Fabrication d'emballages métalliques légers",
  "25.93Z": "Fabrication d'articles en fils métalliques",
  "25.94Z": "Fabrication de vis, boulons, rivets",
  "25.99A": "Fabrication d'articles métalliques ménagers",
  "25.99B": "Fabrication d'autres articles métalliques",
  "26.11Z": "Fabrication de composants électroniques",
  "26.12Z": "Fabrication de cartes électroniques",
  "26.20Z": "Fabrication d'ordinateurs et d'équipements périphériques",
  "26.30Z": "Fabrication d'équipements de communication",
  "26.40Z": "Fabrication de produits électroniques grand public",
  "26.51A": "Fabrication d'équipements d'aide à la navigation",
  "26.51B": "Fabrication d'instrumentation scientifique",
  "26.52Z": "Horlogerie",
  "26.60Z": "Fabrication d'équipements d'irradiation médicale",
  "26.70Z": "Fabrication de matériels optique et photographique",
  "26.80Z": "Fabrication de supports magnétiques et optiques",
  "27.11Z": "Fabrication de moteurs, génératrices et transformateurs",
  "27.12Z": "Fabrication de matériel de distribution électrique",
  "27.20Z": "Fabrication de piles et accumulateurs",
  "27.31Z": "Fabrication de câbles de fibres optiques",
  "27.32Z": "Fabrication d'autres fils et câbles électroniques",
  "27.33Z": "Fabrication d'appareillage électrique",
  "27.40Z": "Fabrication d'équipements d'éclairage",
  "27.51Z": "Fabrication d'appareils électroménagers",
  "27.52Z": "Fabrication d'appareils ménagers non électriques",
  "27.90Z": "Fabrication d'autres matériels électriques",
  "28.11Z": "Fabrication de moteurs et turbines",
  "28.12Z": "Fabrication d'équipements hydrauliques et pneumatiques",
  "28.13Z": "Fabrication d'autres pompes et compresseurs",
  "28.14Z": "Fabrication d'autres articles de robinetterie",
  "28.15Z": "Fabrication d'engrenages et organes mécaniques",
  "28.21Z": "Fabrication de fours et brûleurs",
  "28.22Z": "Fabrication de matériel de levage et de manutention",
  "28.23Z": "Fabrication de machines de bureau",
  "28.24Z": "Fabrication d'outillage portatif",
  "28.25Z": "Fabrication d'équipements de refroidissement industriel",
  "28.29A": "Fabrication d'équipements d'emballage",
  "28.29B": "Fabrication d'autres machines d'usage général",
  "28.30Z": "Fabrication de machines agricoles",
  "28.41Z": "Fabrication de machines de formage des métaux",
  "28.49Z": "Fabrication d'autres machines de travail des métaux",
  "28.92Z": "Fabrication de machines pour l'extraction ou la construction",
  "28.93Z": "Fabrication de machines pour l'industrie agro-alimentaire",
  "28.94Z": "Fabrication de machines pour les industries textiles",
  "28.95Z": "Fabrication de machines pour l'industrie du papier",
  "28.96Z": "Fabrication de machines pour le travail du caoutchouc",
  "28.99A": "Fabrication de machines d'imprimerie",
  "28.99B": "Fabrication d'autres machines spécialisées",
  "29.10Z": "Construction de véhicules automobiles",
  "29.20Z": "Fabrication de carrosseries",
  "29.31Z": "Fabrication d'équipements électriques et électroniques automobiles",
  "29.32Z": "Fabrication d'autres équipements automobiles",
  "30.11Z": "Construction de navires de commerce",
  "30.12Z": "Construction de bateaux de plaisance",
  "30.20Z": "Construction de locomotives et de matériel ferroviaire roulant",
  "30.30Z": "Construction aéronautique et spatiale",
  "30.40Z": "Construction de véhicules militaires de combat",
  "30.91Z": "Fabrication de motocycles",
  "30.92Z": "Fabrication de bicyclettes et de véhicules pour invalides",
  "30.99Z": "Fabrication d'autres équipements de transport",
  "31.01Z": "Fabrication de meubles de bureau et de magasin",
  "31.02Z": "Fabrication de meubles de cuisine",
  "31.03Z": "Fabrication de matelas",
  "31.09A": "Fabrication de sièges d'ameublement d'intérieur",
  "31.09B": "Fabrication d'autres meubles et industries connexes",
  "32.11Z": "Frappe de monnaie",
  "32.12Z": "Fabrication d'articles de joaillerie et bijouterie",
  "32.13Z": "Fabrication d'articles de bijouterie fantaisie",
  "32.20Z": "Fabrication d'instruments de musique",
  "32.30Z": "Fabrication d'articles de sport",
  "32.40Z": "Fabrication de jeux et jouets",
  "32.50A": "Fabrication de matériel médico-chirurgical",
  "32.50B": "Fabrication de lunettes",
  "32.91Z": "Fabrication d'articles de brosserie",
  "32.99Z": "Autres activités manufacturières",
  "33.11Z": "Réparation d'ouvrages en métaux",
  "33.12Z": "Réparation de machines et équipements mécaniques",
  "33.13Z": "Réparation de matériels électroniques",
  "33.14Z": "Réparation d'équipements électriques",
  "33.15Z": "Réparation et maintenance navale",
  "33.16Z": "Réparation et maintenance d'aéronefs",
  "33.17Z": "Réparation et maintenance d'autres équipements de transport",
  "33.19Z": "Réparation d'autres équipements",
  "33.20A": "Installation de structures métalliques",
  "33.20B": "Installation de machines et équipements mécaniques",
  "33.20C": "Conception d'ensembles et assemblages",
  "33.20D": "Installation d'équipements électriques",

  // ── D / E – Énergie, eau, déchets
  "35.11Z": "Production d'électricité",
  "35.12Z": "Transport d'électricité",
  "35.13Z": "Distribution d'électricité",
  "35.14Z": "Commerce d'électricité",
  "35.21Z": "Production de combustibles gazeux",
  "35.22Z": "Distribution de combustibles gazeux",
  "35.23Z": "Commerce de gaz",
  "35.30Z": "Production et distribution de vapeur",
  "36.00Z": "Captage, traitement et distribution d'eau",
  "37.00Z": "Collecte et traitement des eaux usées",
  "38.11Z": "Collecte des déchets non dangereux",
  "38.12Z": "Collecte des déchets dangereux",
  "38.21Z": "Traitement et élimination des déchets non dangereux",
  "38.22Z": "Traitement et élimination des déchets dangereux",
  "38.31Z": "Démantèlement d'épaves",
  "38.32Z": "Récupération de déchets triés",
  "39.00Z": "Dépollution et autres services de gestion des déchets",

  // ── F – Construction
  "41.10A": "Promotion immobilière de logements",
  "41.10B": "Promotion immobilière de bureaux",
  "41.10C": "Promotion immobilière d'autres bâtiments",
  "41.10D": "Supports de projets immobiliers",
  "41.20A": "Construction de maisons individuelles",
  "41.20B": "Construction d'autres bâtiments résidentiels",
  "42.11Z": "Construction de routes et autoroutes",
  "42.12Z": "Construction de voies ferrées",
  "42.13A": "Construction d'ouvrages d'art et de ponts",
  "42.13B": "Construction et entretien de tunnels",
  "42.21Z": "Construction de réseaux d'irrigation",
  "42.22Z": "Construction de réseaux électriques et de télécommunications",
  "42.91Z": "Construction d'ouvrages maritimes et fluviaux",
  "42.99Z": "Construction d'autres ouvrages de génie civil",
  "43.11Z": "Travaux de démolition",
  "43.12A": "Travaux de terrassement courants",
  "43.12B": "Travaux de terrassement spécialisés ou de grande masse",
  "43.13Z": "Forages et sondages",
  "43.21A": "Travaux d'installation électrique dans tous locaux",
  "43.21B": "Travaux d'installation électrique sur la voie publique",
  "43.22A": "Travaux d'installation d'eau et de gaz",
  "43.22B": "Travaux d'installation d'équipements thermiques",
  "43.29A": "Travaux d'isolation",
  "43.29B": "Autres travaux d'installation",
  "43.31Z": "Travaux de plâtrerie",
  "43.32A": "Travaux de menuiserie bois et PVC",
  "43.32B": "Travaux de menuiserie métallique et serrurerie",
  "43.32C": "Agencement de lieux de vente",
  "43.33Z": "Travaux de revêtement des sols et des murs",
  "43.34Z": "Travaux de peinture et vitrerie",
  "43.39Z": "Autres travaux de finition",
  "43.99A": "Travaux d'étanchéification",
  "43.99B": "Travaux de montage de structures métalliques",
  "43.99C": "Travaux de maçonnerie générale",
  "43.99D": "Autres travaux spécialisés de construction",
  "43.99E": "Location avec opérateur de matériel de construction",

  // ── G – Commerce
  "45.11Z": "Commerce de voitures et de véhicules automobiles légers",
  "45.19Z": "Commerce d'autres véhicules automobiles",
  "45.20A": "Entretien et réparation de véhicules automobiles légers",
  "45.20B": "Entretien et réparation d'autres véhicules automobiles",
  "45.31Z": "Commerce de gros d'équipements automobiles",
  "45.32Z": "Commerce de détail d'équipements automobiles",
  "45.40Z": "Commerce et réparation de motocycles",
  "46.11Z": "Intermédiaires du commerce en matières premières agricoles",
  "46.12A": "Centrales d'achats de carburant",
  "46.12B": "Autres intermédiaires du commerce en combustibles",
  "46.13Z": "Intermédiaires du commerce en bois et matériaux de construction",
  "46.14Z": "Intermédiaires du commerce en machines",
  "46.15Z": "Intermédiaires du commerce en meubles",
  "46.16Z": "Intermédiaires du commerce en textiles, habillement",
  "46.17A": "Centrales d'achats alimentaires",
  "46.17B": "Autres intermédiaires du commerce en denrées",
  "46.18Z": "Intermédiaires spécialisés dans le commerce d'autres produits",
  "46.19A": "Centrales d'achats non alimentaires",
  "46.19B": "Autres intermédiaires du commerce général",
  "46.21Z": "Commerce de gros de céréales, légumineuses",
  "46.22Z": "Commerce de gros de fleurs et plantes",
  "46.23Z": "Commerce de gros d'animaux vivants",
  "46.24Z": "Commerce de gros de cuirs et peaux",
  "46.31Z": "Commerce de gros de fruits et légumes",
  "46.32A": "Commerce de gros de viande",
  "46.32B": "Commerce de gros de produits à base de viande",
  "46.33Z": "Commerce de gros de produits laitiers",
  "46.34Z": "Commerce de gros de boissons",
  "46.35Z": "Commerce de gros de produits à base de tabac",
  "46.36Z": "Commerce de gros de sucre, chocolat",
  "46.37Z": "Commerce de gros de café, thé, cacao",
  "46.38A": "Commerce de gros de poissons, crustacés",
  "46.38B": "Commerce de gros d'autres produits alimentaires",
  "46.39A": "Commerce de gros de produits surgelés",
  "46.39B": "Commerce de gros alimentaire non spécialisé",
  "46.41Z": "Commerce de gros de textiles",
  "46.42Z": "Commerce de gros d'habillement",
  "46.43Z": "Commerce de gros d'appareils électroménagers",
  "46.44Z": "Commerce de gros de vaisselle, verrerie",
  "46.45Z": "Commerce de gros de parfumerie et de produits de beauté",
  "46.46Z": "Commerce de gros de produits pharmaceutiques",
  "46.47Z": "Commerce de gros de meubles",
  "46.48Z": "Commerce de gros d'articles d'horlogerie et de bijouterie",
  "46.49Z": "Commerce de gros d'autres biens de consommation",
  "46.51Z": "Commerce de gros d'ordinateurs et équipements périphériques",
  "46.52Z": "Commerce de gros de composants et d'équipements électroniques",
  "46.61Z": "Commerce de gros de machines agricoles",
  "46.62Z": "Commerce de gros de machines de bureau",
  "46.63Z": "Commerce de gros de machines pour l'extraction",
  "46.64Z": "Commerce de gros de machines pour les industries textiles",
  "46.65Z": "Commerce de gros de mobilier de bureau",
  "46.66Z": "Commerce de gros d'autres machines et équipements de bureau",
  "46.69A": "Commerce de gros de matériel électrique",
  "46.69B": "Commerce de gros de fournitures et équipements industriels",
  "46.69C": "Commerce de gros de fournitures et équipements divers",
  "46.71Z": "Commerce de gros de combustibles",
  "46.72Z": "Commerce de gros de minerais et métaux",
  "46.73A": "Commerce de gros de bois et matériaux de construction",
  "46.73B": "Commerce de gros d'appareils sanitaires et de chauffage",
  "46.74A": "Commerce de gros de quincaillerie",
  "46.74B": "Commerce de gros de fournitures pour la plomberie",
  "46.75Z": "Commerce de gros de produits chimiques",
  "46.76Z": "Commerce de gros d'autres produits intermédiaires",
  "46.77Z": "Commerce de gros de déchets et débris",
  "46.90Z": "Commerce de gros non spécialisé",
  "47.11A": "Épiceries et autres magasins d'alimentation en gestion propre",
  "47.11B": "Commerce d'alimentation générale",
  "47.11C": "Supérettes",
  "47.11D": "Supermarchés",
  "47.11E": "Hard-discount et autres libres-services alimentaires",
  "47.11F": "Hypermarchés",
  "47.19A": "Grands magasins",
  "47.19B": "Autres commerces de détail non spécialisés",
  "47.21Z": "Commerce de détail de fruits et légumes",
  "47.22Z": "Commerce de détail de viande",
  "47.23Z": "Commerce de détail de poisson",
  "47.24Z": "Commerce de détail de pain, pâtisserie",
  "47.25Z": "Commerce de détail de boissons",
  "47.26Z": "Commerce de détail de tabac",
  "47.29Z": "Autres commerces de détail alimentaires en magasin spécialisé",
  "47.30Z": "Commerce de détail de carburants",
  "47.41Z": "Commerce de détail d'ordinateurs, unités périphériques et logiciels",
  "47.42Z": "Commerce de détail de matériels de télécommunication",
  "47.43Z": "Commerce de détail de matériels audio et vidéo",
  "47.51Z": "Commerce de détail de textiles",
  "47.52A": "Commerce de détail de quincaillerie, peintures et verres",
  "47.52B": "Commerce de détail de matériaux de construction",
  "47.53Z": "Commerce de détail de tapis, moquettes et revêtements",
  "47.54Z": "Commerce de détail d'appareils électroménagers",
  "47.59A": "Commerce de détail de meubles",
  "47.59B": "Commerce de détail d'autres équipements du foyer",
  "47.61Z": "Commerce de détail de livres",
  "47.62Z": "Commerce de détail de journaux et papeterie",
  "47.63Z": "Commerce de détail d'enregistrements musicaux et vidéo",
  "47.64Z": "Commerce de détail d'articles de sport",
  "47.65Z": "Commerce de détail de jeux et jouets",
  "47.71Z": "Commerce de détail d'habillement",
  "47.72A": "Commerce de détail de la chaussure",
  "47.72B": "Commerce de détail de maroquinerie et d'articles de voyage",
  "47.73Z": "Commerce de détail de produits pharmaceutiques",
  "47.74Z": "Commerce de détail d'articles médicaux et orthopédiques",
  "47.75Z": "Commerce de détail de parfumerie et de produits de beauté",
  "47.76Z": "Commerce de détail de fleurs, plantes, graines",
  "47.77Z": "Commerce de détail d'articles d'horlogerie et de bijouterie",
  "47.78A": "Commerces de détail d'optique",
  "47.78B": "Commerce de détail de charbons et combustibles",
  "47.78C": "Autres commerces de détail spécialisés divers",
  "47.79Z": "Commerce de détail de biens d'occasion",
  "47.81Z": "Commerce de détail alimentaire sur éventaires et marchés",
  "47.82Z": "Commerce de détail de textiles, habillement sur marchés",
  "47.89Z": "Autres commerces de détail sur éventaires et marchés",
  "47.91A": "Vente à distance sur catalogue général",
  "47.91B": "Vente à distance sur catalogue spécialisé",
  "47.99A": "Vente à domicile",
  "47.99B": "Vente par automates et autres commerces hors magasin",

  // ── H – Transport et entreposage
  "49.10Z": "Transport ferroviaire interurbain de voyageurs",
  "49.20Z": "Transports ferroviaires de fret",
  "49.31Z": "Transports urbains et suburbains de voyageurs",
  "49.32Z": "Transports de voyageurs par taxis",
  "49.39A": "Transports routiers réguliers de voyageurs",
  "49.39B": "Autres transports routiers de voyageurs",
  "49.39C": "Téléphériques et remontées mécaniques",
  "49.41A": "Transports routiers de fret interurbains",
  "49.41B": "Transports routiers de fret de proximité",
  "49.41C": "Location de camions avec chauffeur",
  "49.42Z": "Services de déménagement",
  "49.50Z": "Transports par conduites",
  "50.10Z": "Transports maritimes et côtiers de passagers",
  "50.20Z": "Transports maritimes et côtiers de fret",
  "50.30Z": "Transports fluviaux de passagers",
  "50.40Z": "Transports fluviaux de fret",
  "51.10Z": "Transports aériens de passagers",
  "51.21Z": "Transports aériens de fret",
  "51.22Z": "Transports spatiaux",
  "52.10A": "Entreposage et stockage frigorifique",
  "52.10B": "Entreposage et stockage non frigorifique",
  "52.21Z": "Services auxiliaires des transports terrestres",
  "52.22Z": "Services auxiliaires des transports par eau",
  "52.23Z": "Services auxiliaires des transports aériens",
  "52.24A": "Manutention portuaire",
  "52.24B": "Manutention non portuaire",
  "52.29A": "Messagerie, fret express",
  "52.29B": "Affrètement et organisation des transports",
  "53.10Z": "Activités de poste dans le cadre d'une obligation de service universel",
  "53.20Z": "Autres activités de poste et de courrier",

  // ── I – Hébergement et restauration
  "55.10Z": "Hôtels et hébergement similaire",
  "55.20Z": "Hébergement touristique et autre hébergement de courte durée",
  "55.30Z": "Terrains de camping et parcs pour caravanes",
  "55.90Z": "Autres hébergements",
  "56.10A": "Restauration traditionnelle",
  "56.10B": "Cafétérias et autres libres-services",
  "56.10C": "Restauration de type rapide",
  "56.21Z": "Services des traiteurs",
  "56.29A": "Restauration collective sous contrat",
  "56.29B": "Autres services de restauration collective",
  "56.30Z": "Débits de boissons",

  // ── J – Information et communication
  "58.11Z": "Édition de livres",
  "58.12Z": "Édition de répertoires et de fichiers d'adresses",
  "58.13Z": "Édition de journaux",
  "58.14Z": "Édition de revues et périodiques",
  "58.19Z": "Autres activités d'édition",
  "58.21Z": "Édition de jeux électroniques",
  "58.29A": "Édition de logiciels systèmes et de réseau",
  "58.29B": "Édition de logiciels outils de développement",
  "58.29C": "Édition de logiciels applicatifs",
  "59.11A": "Production de films et de programmes pour la télévision",
  "59.11B": "Production de films institutionnels et publicitaires",
  "59.11C": "Production de films pour le cinéma",
  "59.12Z": "Post-production de films cinématographiques",
  "59.13A": "Distribution de films cinématographiques",
  "59.13B": "Édition et distribution vidéo",
  "59.14Z": "Projection de films cinématographiques",
  "59.20Z": "Enregistrement sonore et édition musicale",
  "60.10Z": "Édition et diffusion de programmes radio",
  "60.20A": "Edition de chaînes généralistes",
  "60.20B": "Edition de chaînes thématiques",
  "61.10Z": "Télécommunications filaires",
  "61.20Z": "Télécommunications sans fil",
  "61.30Z": "Télécommunications par satellite",
  "61.90Z": "Autres activités de télécommunication",
  "62.01Z": "Programmation informatique",
  "62.02A": "Conseil en systèmes et logiciels informatiques",
  "62.02B": "Tierce maintenance de systèmes et d'applications informatiques",
  "62.03Z": "Gestion d'installations informatiques",
  "62.09Z": "Autres activités informatiques",
  "63.11Z": "Traitement de données, hébergement et activités connexes",
  "63.12Z": "Portails Internet",
  "63.91Z": "Activités des agences de presse",
  "63.99Z": "Autres services d'information",

  // ── K – Activités financières et d'assurance
  "64.11Z": "Activités de banque centrale",
  "64.19Z": "Autres intermédiations monétaires",
  "64.20Z": "Activités des sociétés holding",
  "64.30Z": "Fonds de placement et entités financières similaires",
  "64.91Z": "Crédit-bail",
  "64.92Z": "Autre distribution de crédit",
  "64.99Z": "Autres activités des services financiers",
  "65.11Z": "Assurance vie",
  "65.12Z": "Autres assurances",
  "65.20Z": "Réassurance",
  "65.30Z": "Caisses de retraite",
  "66.11Z": "Administration de marchés financiers",
  "66.12Z": "Courtage de valeurs mobilières et de marchandises",
  "66.19A": "Supports juridiques de gestion de patrimoine mobilier",
  "66.19B": "Autres activités auxiliaires de services financiers",
  "66.21Z": "Évaluation des risques et dommages",
  "66.22Z": "Activités des agents et courtiers d'assurances",
  "66.29Z": "Autres activités auxiliaires d'assurance",
  "66.30Z": "Gestion de fonds",

  // ── L – Activités immobilières
  "68.10Z": "Activités des marchands de biens immobiliers",
  "68.20A": "Location de logements",
  "68.20B": "Location de terrains et d'autres biens immobiliers",
  "68.31Z": "Agences immobilières",
  "68.32A": "Administration d'immeubles résidentiels",
  "68.32B": "Administration d'autres biens immobiliers",

  // ── M – Activités spécialisées, scientifiques et techniques
  "69.10Z": "Activités juridiques",
  "69.20Z": "Activités comptables",
  "70.10Z": "Activités des sièges sociaux",
  "70.21Z": "Conseil en relations publiques et communication",
  "70.22Z": "Conseil pour les affaires et autres conseils de gestion",
  "71.11Z": "Activités d'architecture",
  "71.12A": "Activité des géomètres",
  "71.12B": "Ingénierie, études techniques",
  "71.20A": "Contrôle technique automobile",
  "71.20B": "Analyses, essais et inspections techniques",
  "72.11Z": "Recherche-développement en biotechnologie",
  "72.19Z": "Autre recherche-développement en sciences physiques",
  "72.20Z": "Recherche-développement en sciences humaines et sociales",
  "73.11Z": "Activités des agences de publicité",
  "73.12Z": "Régie publicitaire de médias",
  "73.20Z": "Études de marché et sondages d'opinion",
  "74.10Z": "Activités spécialisées de design",
  "74.20Z": "Activités photographiques",
  "74.30Z": "Traduction et interprétation",
  "74.90A": "Activités des économistes de la construction",
  "74.90B": "Activités spécialisées, scientifiques et techniques diverses",
  "75.00Z": "Activités vétérinaires",

  // ── N – Activités de services administratifs et de soutien
  "77.11A": "Location de courte durée de voitures",
  "77.11B": "Location de longue durée de voitures",
  "77.12Z": "Location et location-bail de camions",
  "77.21Z": "Location et location-bail d'articles de loisirs",
  "77.22Z": "Location de cassettes vidéo et disques",
  "77.29Z": "Location et location-bail d'autres biens personnels",
  "77.31Z": "Location et location-bail de machines agricoles",
  "77.32Z": "Location et location-bail de machines de chantier",
  "77.33Z": "Location et location-bail de machines de bureau",
  "77.34Z": "Location et location-bail de matériels de transport par eau",
  "77.35Z": "Location et location-bail de matériels de transport aérien",
  "77.39Z": "Location et location-bail d'autres machines",
  "77.40Z": "Location-bail de propriété intellectuelle",
  "78.10Z": "Activités des agences de placement de main-d'œuvre",
  "78.20Z": "Activités des agences de travail temporaire",
  "78.30Z": "Autre mise à disposition de ressources humaines",
  "79.11Z": "Activités des agences de voyage",
  "79.12Z": "Activités des voyagistes",
  "79.90Z": "Autres services de réservation",
  "80.10Z": "Activités de sécurité privée",
  "80.20Z": "Activités liées aux systèmes de sécurité",
  "80.30Z": "Activités d'enquête",
  "81.10Z": "Activités combinées de soutien lié aux bâtiments",
  "81.21Z": "Nettoyage courant des bâtiments",
  "81.22Z": "Autres activités de nettoyage des bâtiments",
  "81.29A": "Désinfection, désinsectisation, dératisation",
  "81.29B": "Autres activités de nettoyage",
  "81.30Z": "Services d'aménagement paysager",
  "82.11Z": "Services administratifs combinés de bureau",
  "82.19Z": "Photocopie, préparation de documents",
  "82.20Z": "Activités de centres d'appels",
  "82.30Z": "Organisation de foires, salons professionnels et congrès",
  "82.91Z": "Activités des agences de recouvrement de factures",
  "82.92Z": "Activités de conditionnement",
  "82.99Z": "Autres activités de soutien aux entreprises",

  // ── P – Enseignement
  "85.10Z": "Enseignement pré-primaire",
  "85.20Z": "Enseignement primaire",
  "85.31Z": "Enseignement secondaire général",
  "85.32Z": "Enseignement secondaire technique ou professionnel",
  "85.41Z": "Enseignement post-secondaire non supérieur",
  "85.42Z": "Enseignement supérieur",
  "85.51Z": "Enseignement de disciplines sportives et d'activités de loisirs",
  "85.52Z": "Enseignement culturel",
  "85.53Z": "Enseignement de la conduite",
  "85.59A": "Formation continue d'adultes",
  "85.59B": "Autres enseignements",
  "85.60Z": "Activités de soutien à l'enseignement",

  // ── Q – Santé humaine et action sociale
  "86.10Z": "Activités hospitalières",
  "86.21Z": "Activité des médecins généralistes",
  "86.22A": "Activités de radiodiagnostic et radiothérapie",
  "86.22B": "Activités chirurgicales",
  "86.22C": "Autres activités des médecins spécialistes",
  "86.23Z": "Pratique dentaire",
  "86.90A": "Ambulances",
  "86.90B": "Laboratoires d'analyses médicales",
  "86.90C": "Centres de collecte et banques d'organes",
  "86.90D": "Activités des infirmiers et sages-femmes",
  "86.90E": "Activités des professionnels de la rééducation",
  "86.90F": "Activités de santé humaine non classées ailleurs",
  "87.10A": "Hébergement médicalisé pour personnes âgées",
  "87.10B": "Hébergement médicalisé pour enfants handicapés",
  "87.10C": "Hébergement médicalisé pour adultes handicapés",
  "87.20A": "Hébergement social pour handicapés mentaux",
  "87.20B": "Hébergement social pour toxicomanes",
  "87.30A": "Hébergement social pour personnes âgées",
  "87.30B": "Hébergement social pour adultes handicapés",
  "87.90A": "Hébergement social pour enfants en difficultés",
  "87.90B": "Hébergement social pour adultes et familles en difficultés",
  "88.10A": "Aide à domicile",
  "88.10B": "Accueil ou accompagnement sans hébergement d'adultes handicapés",
  "88.10C": "Aide par le travail",
  "88.91A": "Accueil de jeunes enfants",
  "88.91B": "Accueil ou accompagnement sans hébergement d'enfants handicapés",
  "88.99A": "Autre accueil ou accompagnement sans hébergement d'enfants",
  "88.99B": "Action sociale sans hébergement n.c.a.",

  // ── R – Arts, spectacles et activités récréatives
  "90.01Z": "Arts du spectacle vivant",
  "90.02Z": "Activités de soutien au spectacle vivant",
  "90.03A": "Création artistique relevant des arts plastiques",
  "90.03B": "Autre création artistique",
  "90.04Z": "Gestion de salles de spectacles",
  "91.01Z": "Gestion des bibliothèques et des archives",
  "91.02Z": "Gestion des musées",
  "91.03Z": "Gestion des sites et monuments historiques",
  "91.04Z": "Gestion des jardins botaniques et zoologiques",
  "92.00Z": "Organisation de jeux de hasard et d'argent",
  "93.11Z": "Gestion d'installations sportives",
  "93.12Z": "Activités de clubs de sports",
  "93.13Z": "Activités des centres de culture physique",
  "93.19Z": "Autres activités liées au sport",
  "93.21Z": "Activités des parcs d'attractions et parcs à thèmes",
  "93.29Z": "Autres activités récréatives et de loisirs",

  // ── S – Autres activités de services
  "94.11Z": "Activités des organisations patronales et consulaires",
  "94.12Z": "Activités des organisations professionnelles",
  "94.20Z": "Activités des syndicats de salariés",
  "94.91Z": "Activités des organisations religieuses",
  "94.92Z": "Activités des organisations politiques",
  "94.99Z": "Autres organisations fonctionnant par adhésion volontaire",
  "95.11Z": "Réparation d'ordinateurs et d'équipements périphériques",
  "95.12Z": "Réparation d'équipements de communication",
  "95.21Z": "Réparation de produits électroniques grand public",
  "95.22Z": "Réparation d'appareils électroménagers",
  "95.23Z": "Réparation de chaussures et d'articles en cuir",
  "95.24Z": "Réparation de meubles et d'équipements du foyer",
  "95.25Z": "Réparation d'articles d'horlogerie et de bijouterie",
  "95.29Z": "Réparation d'autres biens personnels et domestiques",
  "96.01A": "Blanchisserie-teinturerie de gros",
  "96.01B": "Blanchisserie-teinturerie de détail",
  "96.02A": "Coiffure",
  "96.02B": "Soins de beauté",
  "96.03Z": "Services funéraires",
  "96.04Z": "Entretien corporel",
  "96.09Z": "Autres services personnels",
};

// Codes anciens format (avant NAF 2008) encore présents dans certaines entreprises
const NAF_LEGACY: Record<string, string> = {
  "74.1G": "Design graphique et communication visuelle",
  "74.4A": "Publicité",
  "74.4B": "Gestion de supports publicitaires",
  "50.5Z": "Commerce de détail de carburants",
  "72.1Z": "Consultation en systèmes et logiciels informatiques",
  "72.2Z": "Réalisation de logiciels",
  "72.3Z": "Traitement de données",
  "72.4Z": "Activités de bases de données",
  "72.6Z": "Autres activités informatiques",
  "74.1A": "Activités juridiques",
  "74.1B": "Activités comptables",
  "74.1C": "Études de marché et sondages",
  "74.1D": "Conseil pour les affaires et le management",
  "74.1E": "Administration d'entreprises",
  "74.3Z": "Tests et analyses techniques",
  "74.8A": "Laboratoires photographiques",
  "74.8B": "Traduction et interprétation",
  "74.8C": "Secrétariat et traduction",
  "74.8D": "Routage",
  "74.8E": "Autres services aux entreprises",
  "92.1A": "Production de films cinématographiques",
  "92.1B": "Distribution de films",
  "92.2A": "Production de programmes de radio",
  "92.2B": "Production de programmes de télévision",
  "93.0A": "Blanchisserie-teinturerie",
  "52.1Z": "Commerce de détail en magasin non spécialisé",
  "51.1A": "Intermédiaires du commerce",
  "55.1A": "Hôtels avec restaurant",
  "55.1B": "Hôtels sans restaurant",
  "55.3A": "Restauration de type traditionnel",
  "55.3B": "Restauration rapide",
};

export function nafLabel(code: string): string {
  return NAF_LABELS[code] ?? NAF_LEGACY[code] ?? code;
}
